"use client";

import { useEffect, useMemo, useState } from "react";
import { calcularMaterial } from "@/lib/calculo";
import { descargar, dxfContorno } from "@/lib/dxf";
import {
  calcularEngranaje, calcularPareja, contornoEngranaje,
  DIAMETRAL_PITCH, MODULOS_SERIE1, MODULOS_SERIE2,
} from "@/lib/engranajes";
import { kg, largo, num as fmtNum, unidad, type Unidad } from "@/lib/formato";
import type { Idioma } from "@/lib/idioma";
import { aPuntos } from "@/lib/perfil";
import { Icono } from "./Iconos";

type Sistema = "modulo" | "dp";
const num = (t: string) => parseFloat(t.replace(",", "."));

const TX = {
  es: {
    datos: "Datos del engranaje", datosSub: "Recto, de evolvente, perfil ISO 53.",
    sistema: "Sistema", modulo: "Módulo (métrico)", dp: "Diametral pitch (pulg.)", serie1: "Serie 1 (preferente)", serie2: "Serie 2",
    moduloX: "Módulo", equivale: "equivale a m",
    dientes: "Dientes (Z)", angulo: "Ángulo de presión", x: "Desplazamiento de perfil x", b: "Ancho del diente b (mm)",
    compa: "Engranaje compañero (opcional)", z2: "Dientes Z2", x2: "Desplazamiento x2", ej: "ej. 40",
    unidades: "Unidades", pulgadas: "pulgadas", agujero: "Agujero (mm)", sugerido: "sugerido",
    dxf: "Descargar DXF para corte", dxfArchivo: "engranaje",
    dxfNota: "Perfil generado simulando el tallado con la cremallera ISO 53 (evolvente, pie redondeado y rebaje reales), en mm. Capa REFERENCIA con el diámetro primitivo.",
    medidas: "Medidas del engranaje", engranaje: "Engranaje", recto: "Recto", mEquiv: "m equivalente", imprimir: "Imprimir ficha", z: "Z",
    diametros: "Diámetros", dPrim: "Diámetro primitivo", dExt: "Diámetro exterior", dFondo: "Diámetro de fondo", dBase: "Diámetro base",
    control: "Control con pie de metro", wk: (k: number) => `Medida sobre ${k} dientes`, sc: "Espesor cordal del diente", hc: "Altura cordal (para el calibre)",
    controlNota: (k: number) => `Wk: abarque ${k} dientes con las caras planas del pie de metro. El espesor cordal se mide con calibre de dientes, ajustado a la altura hc desde la punta.`,
    diente: "Diente", paso: "Paso circular", s: "Espesor en el primitivo (arco)", h: "Altura total del diente", hahf: "Altura de cabeza / de pie", c: "Juego en el fondo",
    pareja: "Pareja de engranajes", a: "Distancia entre centros", i: "Relación de transmisión", da2: (z: number) => `Diámetro exterior Z${z}`, aw: "Ángulo de presión de trabajo", eps: "Razón de contacto",
    epsBaja: "⚠ Razón de contacto baja (bajo 1,2): engrane brusco.", epsOk: "Razón de contacto adecuada (sobre 1,2).",
    material: "Material de partida (acero)", sobremedida: "Sobremedida (mm)", corteD: "Ø de corte", corteL: "Largo / espesor de corte", pesoB: "Peso bruto", pesoN: "Peso aprox. terminado",
    revision: "Revisión",
    rebaje: (z: number, a: string, zmin: number, x: string) => `Con ${z} dientes a ${a}° la herramienta rebaja el pie del diente (mínimo sin rebaje: ${zmin} dientes). Para evitarlo use un desplazamiento x ≥ ${x}.`,
    sinRebaje: "Sin rebaje en el pie del diente.",
    punta: (s: string) => `Diente en punta: espesor en la cabeza de ${s} (menos de 0,2·m). Reduzca el desplazamiento.`,
    aviso: "Fórmulas ISO 53 / DIN 867 para dentado recto exterior. Verifique tolerancias y juego entre dientes según la aplicación.",
    dibujo: (z: number) => `Engranaje de ${z} dientes`,
  },
  en: {
    datos: "Gear data", datosSub: "Spur, involute, ISO 53 basic rack.",
    sistema: "System", modulo: "Module (metric)", dp: "Diametral pitch (inch)", serie1: "Series 1 (preferred)", serie2: "Series 2",
    moduloX: "Module", equivale: "equals m",
    dientes: "Teeth (N)", angulo: "Pressure angle", x: "Profile shift x", b: "Face width b (mm)",
    compa: "Mating gear (optional)", z2: "Teeth N2", x2: "Profile shift x2", ej: "e.g. 40",
    unidades: "Units", pulgadas: "inches", agujero: "Bore (mm)", sugerido: "suggested",
    dxf: "Download DXF for cutting", dxfArchivo: "gear",
    dxfNota: "Profile generated by simulating generation with the ISO 53 rack (true involute, root fillet and undercut), in mm. REFERENCE layer with the pitch circle.",
    medidas: "Gear dimensions", engranaje: "Gear", recto: "Spur", mEquiv: "equivalent m", imprimir: "Print sheet", z: "N",
    diametros: "Diameters", dPrim: "Pitch diameter", dExt: "Outside diameter", dFondo: "Root diameter", dBase: "Base diameter",
    control: "Inspection with a caliper", wk: (k: number) => `Span measurement over ${k} teeth`, sc: "Chordal tooth thickness", hc: "Chordal addendum (for gear tooth caliper)",
    controlNota: (k: number) => `Wk: span ${k} teeth with the flat jaws of the caliper. Chordal thickness is measured with a gear tooth caliper set to the chordal addendum hc.`,
    diente: "Tooth", paso: "Circular pitch", s: "Tooth thickness at pitch circle (arc)", h: "Whole depth", hahf: "Addendum / dedendum", c: "Bottom clearance",
    pareja: "Gear pair", a: "Center distance", i: "Gear ratio", da2: (z: number) => `Outside diameter N${z}`, aw: "Working pressure angle", eps: "Contact ratio",
    epsBaja: "⚠ Low contact ratio (below 1.2): rough meshing.", epsOk: "Adequate contact ratio (above 1.2).",
    material: "Stock material (steel)", sobremedida: "Allowance (mm)", corteD: "Cut Ø", corteL: "Cut length / thickness", pesoB: "Stock weight", pesoN: "Approx. finished weight",
    revision: "Check",
    rebaje: (z: number, a: string, zmin: number, x: string) => `With ${z} teeth at ${a}° the cutter undercuts the tooth root (minimum without undercut: ${zmin} teeth). To avoid it use a profile shift x ≥ ${x}.`,
    sinRebaje: "No undercut at the tooth root.",
    punta: (s: string) => `Pointed tooth: top land thickness ${s} (less than 0.2·m). Reduce the profile shift.`,
    aviso: "ISO 53 / DIN 867 formulas for external spur gears. Check tolerances and backlash for your application.",
    dibujo: (z: number) => `${z}-tooth gear`,
  },
};

export function CalcEngranajes({ l = "es" }: { l?: Idioma }) {
  const t = TX[l];
  const en = l === "en";
  const [sistema, setSistema] = useState<Sistema>(en ? "dp" : "modulo");
  const [modulo, setModulo] = useState(2);
  const [dp, setDp] = useState(10);
  const [alfa, setAlfa] = useState(20);
  const [z, setZ] = useState(20);
  const [xTxt, setXTxt] = useState("0");
  const [z2Txt, setZ2Txt] = useState("");
  const [x2Txt, setX2Txt] = useState("0");
  const [bTxt, setBTxt] = useState("20");
  const [agujeroTxt, setAgujeroTxt] = useState("");
  const [sobremedida, setSobremedida] = useState(3);
  const [u, setU] = useState<Unidad>(en ? "in" : "mm");

  useEffect(() => {
    const q = new URLSearchParams(window.location.search);
    if (q.get("dp")) { setSistema("dp"); setDp(Number(q.get("dp")) || 10); }
    if (Number(q.get("m")) > 0) { setSistema("modulo"); setModulo(Number(q.get("m"))); }
    const zq = Number(q.get("z")); if (zq >= 6 && zq <= 300) setZ(zq);
    if (q.get("a") === "14.5") setAlfa(14.5);
    if (q.get("x")) setXTxt(q.get("x")!);
    if (q.get("z2")) setZ2Txt(q.get("z2")!);
  }, []);

  const m = sistema === "modulo" ? modulo : 25.4 / dp;
  const zz = Math.min(Math.max(Math.round(z) || 6, 6), 300);
  const x = Math.max(-1, Math.min(1.5, num(xTxt) || 0));
  const z2 = Math.round(num(z2Txt)) || 0;
  const x2 = Math.max(-1, Math.min(1.5, num(x2Txt) || 0));
  const b = num(bTxt) || 0;

  useEffect(() => {
    const q = new URLSearchParams(sistema === "modulo" ? { m: String(modulo) } : { dp: String(dp) });
    q.set("z", String(zz));
    if (alfa !== 20) q.set("a", String(alfa));
    if (x) q.set("x", String(x));
    if (z2 >= 6) q.set("z2", String(z2));
    window.history.replaceState(null, "", `?${q}`);
  }, [sistema, modulo, dp, zz, alfa, x, z2]);

  const g = useMemo(() => calcularEngranaje({ m, z: zz, alfa, x }), [m, zz, alfa, x]);
  const g2 = useMemo(() => (z2 >= 6 && z2 <= 300 ? calcularEngranaje({ m, z: z2, alfa, x: x2 }) : null), [m, z2, alfa, x2]);
  const par = g2 ? calcularPareja(g, g2) : null;
  const vista = useMemo(() => contornoEngranaje(g, -Math.PI / 2 - Math.PI / zz, 36, 160), [g, zz]);

  const agujero = num(agujeroTxt) > 0 ? num(agujeroTxt) : Math.max(Math.round((g.df * 0.3) / 5) * 5, 0);
  const mat = calcularMaterial({ de: g.da, df: g.df, anchoDentado: b, conCubo: false, dCubo: 0, largoTotal: b, agujero, sobremedida });

  const L = (mm: number) => largo(mm, u, l);
  const U = unidad(u);
  const f = (n: number, d = 2) => fmtNum(n, d, l);
  const dec = (v: number) => (en ? String(v) : String(v).replace(".", ","));
  const nombre = sistema === "modulo" ? `m ${dec(m)}` : `DP ${dec(dp)}`;

  const bajarDxf = () => {
    const pts = contornoEngranaje(g, 0, 160, 700);
    const txt = dxfContorno({ puntos: pts, agujero, referencias: [g.d / 2] });
    descargar(`${t.dxfArchivo}-${sistema === "modulo" ? `m${m}` : `DP${dp}`}-${t.z}${zz}${x ? `-x${x}` : ""}.dxf`.replace(/\./g, "_").replace(/_dxf$/, ".dxf"), txt);
  };

  return (
    <div className="calc">
      <section className="panel seleccion" aria-label={t.datos}>
        <header className="panel-cab">
          <span className="panel-ico"><Icono n="engranaje" size={22} /></span>
          <div><h2>{t.datos}</h2><p>{t.datosSub}</p></div>
        </header>

        <div className="campo">
          <span className="etq"><b>1</b> {t.sistema}</span>
          <div className="seg" role="radiogroup" aria-label={t.sistema}>
            {((en ? ["dp", "modulo"] : ["modulo", "dp"]) as Sistema[]).map((s) => (
              <button key={s} role="radio" aria-checked={sistema === s} className={sistema === s ? "on" : ""} onClick={() => setSistema(s)}>{s === "modulo" ? t.modulo : t.dp}</button>
            ))}
          </div>
          <div className="select">
            {sistema === "modulo" ? (
              <select aria-label={t.moduloX} value={modulo} onChange={(e) => setModulo(Number(e.target.value))}>
                <optgroup label={t.serie1}>{MODULOS_SERIE1.map((v) => <option key={v} value={v}>{t.moduloX} {dec(v)}</option>)}</optgroup>
                <optgroup label={t.serie2}>{MODULOS_SERIE2.map((v) => <option key={v} value={v}>{t.moduloX} {dec(v)}</option>)}</optgroup>
              </select>
            ) : (
              <select aria-label="Diametral pitch" value={dp} onChange={(e) => setDp(Number(e.target.value))}>
                {DIAMETRAL_PITCH.map((v) => <option key={v} value={v}>DP {dec(v)} ({t.equivale} {f(25.4 / v, 3)})</option>)}
              </select>
            )}
            <Icono n="chevron" size={18} />
          </div>
        </div>

        <div className="fila2 iguales">
          <div className="campo">
            <label className="etq" htmlFor="ze"><b>2</b> {t.dientes}</label>
            <input id="ze" type="number" min={6} max={300} value={z} onChange={(e) => setZ(Number(e.target.value))} onBlur={() => setZ(zz)} className="num-grande" />
          </div>
          <div className="campo">
            <span className="etq"><b>3</b> {t.angulo}</span>
            <div className="seg chico">
              <button className={alfa === 20 ? "on" : ""} onClick={() => setAlfa(20)}>20°</button>
              <button className={alfa === 14.5 ? "on" : ""} onClick={() => setAlfa(14.5)}>{dec(14.5)}°</button>
            </div>
          </div>
        </div>

        <div className="fila2">
          <label className="mini">{t.x}
            <input type="text" inputMode="decimal" value={xTxt} onChange={(e) => setXTxt(e.target.value)} />
          </label>
          <label className="mini">{t.b}
            <input type="text" inputMode="decimal" value={bTxt} onChange={(e) => setBTxt(e.target.value)} />
          </label>
        </div>

        <div className="campo">
          <span className="etq etq-ico"><Icono n="engranaje" size={17} /> {t.compa}</span>
          <div className="fila2 iguales">
            <label className="mini">{t.z2}<input type="text" inputMode="numeric" placeholder={t.ej} value={z2Txt} onChange={(e) => setZ2Txt(e.target.value)} /></label>
            <label className="mini">{t.x2}<input type="text" inputMode="decimal" value={x2Txt} onChange={(e) => setX2Txt(e.target.value)} /></label>
          </div>
        </div>

        <div className="fila2">
          <div className="campo">
            <span className="etq etq-ico"><Icono n="regla" size={17} /> {t.unidades}</span>
            <div className="seg chico">
              <button className={u === "mm" ? "on" : ""} onClick={() => setU("mm")}>mm</button>
              <button className={u === "in" ? "on" : ""} onClick={() => setU("in")}>{t.pulgadas}</button>
            </div>
          </div>
          <label className="mini">{t.agujero}
            <input type="text" inputMode="decimal" placeholder={`${agujero} (${t.sugerido})`} value={agujeroTxt} onChange={(e) => setAgujeroTxt(e.target.value)} />
          </label>
        </div>

        <div className="vista vista-trans">
          <DibujoEngranaje pts={vista} g={g} agujero={agujero} etiqueta={t.dibujo(zz)} />
        </div>
        <div className="corte no-print">
          <button className="btn-dxf" onClick={bajarDxf}><Icono n="descarga" size={18} /> {t.dxf}</button>
          <p className="nota">{t.dxfNota}</p>
        </div>
      </section>

      <section className="panel resultados" aria-label={t.medidas}>
        <div className="resumen">
          <span className="resumen-ico"><Icono n="engranaje" size={34} /></span>
          <div className="resumen-txt">
            <h2>{t.engranaje} {nombre} · {t.z}{zz}{x ? ` · x = ${f(x, 2)}` : ""}</h2>
            <p>{t.recto}, α = {dec(alfa)}° · ISO 53{sistema === "dp" ? ` · ${t.mEquiv} ${f(m, 3)} mm` : ""}</p>
          </div>
          <button className="btn-prim solo no-print" onClick={() => window.print()}><Icono n="impresora" size={18} /> {t.imprimir}</button>
        </div>

        <div className="tarjetas">
          <Tarjeta t={t.diametros} i="diametro" u={U}>
            <Dato n={t.dPrim} s="d" v={L(g.d)} dest />
            <Dato n={t.dExt} s="da" v={L(g.da)} dest />
            <Dato n={t.dFondo} s="df" v={L(g.df)} dest />
            <Dato n={t.dBase} s="db" v={L(g.db)} />
          </Tarjeta>

          <Tarjeta t={t.control} i="calibre" u={U}>
            <Dato n={t.wk(g.k)} s={`W${g.k}`} v={L(g.wk)} dest />
            <Dato n={t.sc} s="sc" v={L(g.sCordal)} dest />
            <Dato n={t.hc} s="hc" v={L(g.hCordal)} />
            <p className="nota">{t.controlNota(g.k)}</p>
          </Tarjeta>

          <Tarjeta t={t.diente} i="diente" u={U}>
            <Dato n={t.paso} s="p" v={L(g.p)} />
            <Dato n={t.s} s="s" v={L(g.s)} />
            <Dato n={t.h} s="h" v={L(g.h)} dest />
            <Dato n={t.hahf} s="ha/hf" v={`${L(g.ha)} / ${L(g.hf)}`} />
            <Dato n={t.c} s="c" v={L(g.c)} />
          </Tarjeta>

          {par && g2 && (
            <Tarjeta t={t.pareja} i="ancho" u={U}>
              <Dato n={t.a} s="a" v={L(par.a)} dest />
              <Dato n={t.i} s="i" v={`${f(par.relacion, 3)} : 1`} dest />
              <Dato n={t.da2(g2.z)} s="da2" v={L(g2.da)} />
              {(x !== 0 || x2 !== 0) && <Dato n={t.aw} s="αw" v={`${f(par.alfaW, 2)}°`} />}
              <Dato n={t.eps} s="ε" v={f(par.razonContacto, 2)} />
              <p className="nota">{par.razonContacto < 1.2 ? t.epsBaja : t.epsOk}</p>
            </Tarjeta>
          )}

          <Tarjeta t={t.material} i="peso" u="">
            <div className="entradas"><label>{t.sobremedida}<input type="number" min={0} step={0.5} value={sobremedida} onChange={(e) => setSobremedida(Number(e.target.value) || 0)} /></label></div>
            <Dato n={t.corteD} s="" v={`${L(mat.dCorte)} ${U}`} dest />
            <Dato n={t.corteL} s="" v={`${L(mat.largoCorte)} ${U}`} />
            <Dato n={t.pesoB} s="" v={kg(mat.pesoBruto, l)} />
            <Dato n={t.pesoN} s="" v={kg(mat.pesoNeto, l)} />
          </Tarjeta>

          <article className="tarjeta tarjeta-avisos">
            <header><h3><Icono n="escudo" size={20} className="tarjeta-ico" />{t.revision}</h3></header>
            <ul className="avisos">
              {g.rebaje ? (
                <li className="aviso-ojo"><Icono n="info" size={17} /><span>{t.rebaje(zz, dec(alfa), Math.ceil(g.zMinSinRebaje), f(g.xMinSinRebaje, 2))}</span></li>
              ) : (
                <li className="aviso-ok"><Icono n="check" size={17} /><span>{t.sinRebaje}</span></li>
              )}
              {g.puntaAguda && <li className="aviso-mal"><Icono n="info" size={17} /><span>{t.punta(`${L(g.sa)} ${U}`)}</span></li>}
            </ul>
          </article>
        </div>
        <p className="aviso">{t.aviso}</p>
      </section>
    </div>
  );
}

function DibujoEngranaje({ pts, g, agujero, etiqueta }: { pts: [number, number][]; g: ReturnType<typeof calcularEngranaje>; agujero: number; etiqueta: string }) {
  const m = g.da / 2;
  const fs = m * 0.13;
  const xD = -m * 1.22, xDa = m * 1.22, yDf = m * 1.28;
  return (
    <svg viewBox={`${-m * 1.62} ${-m * 1.12} ${m * 3.24} ${m * 2.6}`} className="dibujo-svg" role="img" aria-label={etiqueta}>
      <defs>
        <marker id="fe" viewBox="0 0 10 10" refX="9" refY="5" markerUnits="userSpaceOnUse" markerWidth={m * 0.09} markerHeight={m * 0.09} orient="auto-start-reverse"><path d="M0 1L10 5 0 9z" className="cota-flecha" /></marker>
      </defs>
      <polygon points={aPuntos(pts)} className="d-cuerpo" vectorEffect="non-scaling-stroke" />
      <circle r={g.d / 2} className="d-primitivo" vectorEffect="non-scaling-stroke" />
      {agujero > 0 && <circle r={agujero / 2} className="d-agujero" vectorEffect="non-scaling-stroke" />}
      <g className="cota">
        <path d={`M0 ${-g.d / 2}H${xD - m * 0.05}M0 ${g.d / 2}H${xD - m * 0.05}`} className="cota-ext" vectorEffect="non-scaling-stroke" />
        <path d={`M${xD} ${-g.d / 2}V${g.d / 2}`} markerStart="url(#fe)" markerEnd="url(#fe)" vectorEffect="non-scaling-stroke" />
        <text x={xD - fs * 0.6} y={0} fontSize={fs} textAnchor="end" dominantBaseline="middle">d</text>
      </g>
      <g className="cota">
        <path d={`M0 ${-m}H${xDa + m * 0.05}M0 ${m}H${xDa + m * 0.05}`} className="cota-ext" vectorEffect="non-scaling-stroke" />
        <path d={`M${xDa} ${-m}V${m}`} markerStart="url(#fe)" markerEnd="url(#fe)" vectorEffect="non-scaling-stroke" />
        <text x={xDa + fs * 0.6} y={0} fontSize={fs} dominantBaseline="middle">da</text>
      </g>
      <g className="cota">
        <path d={`M${-g.df / 2} 0V${yDf + m * 0.05}M${g.df / 2} 0V${yDf + m * 0.05}`} className="cota-ext" vectorEffect="non-scaling-stroke" />
        <path d={`M${-g.df / 2} ${yDf}H${g.df / 2}`} markerStart="url(#fe)" markerEnd="url(#fe)" vectorEffect="non-scaling-stroke" />
        <text x={0} y={yDf - fs * 0.45} fontSize={fs} textAnchor="middle">df</text>
      </g>
    </svg>
  );
}

function Tarjeta({ t, i, u, children }: { t: string; i: string; u: string; children: React.ReactNode }) {
  return (
    <article className="tarjeta">
      <header><h3><Icono n={i} size={20} className="tarjeta-ico" />{t}</h3>{u && <span className="u">{u}</span>}</header>
      <dl>{children}</dl>
    </article>
  );
}

function Dato({ n, s, v, dest }: { n: string; s: string; v: string; dest?: boolean }) {
  return (
    <div className={`dato ${dest ? "dest" : ""}`}>
      <dt>{n}{s && <span className="sim">{s}</span>}</dt>
      <dd>{v}</dd>
    </div>
  );
}
